const mongoose = require('mongoose');
const { SETTLEMENT_STATUS } = require('../constants');

const settlementSchema = new mongoose.Schema(
  {
    group: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Group',
      required: true,
      index: true,
    },
    from: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    to: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    amount: {
      type: Number,
      required: true,
      min: 0.01,
    },
    currency: {
      type: String,
      default: 'USD',
    },
    status: {
      type: String,
      enum: Object.values(SETTLEMENT_STATUS),
      default: SETTLEMENT_STATUS.PENDING,
    },
    method: {
      type: String,
      enum: ['cash', 'bank_transfer', 'upi', 'paypal', 'other'],
      default: 'cash',
    },
    note: {
      type: String,
      maxlength: 300,
      default: '',
    },
    settledAt: {
      type: Date,
    },
    recordedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    // Whether this was auto-generated by the smart settlement optimizer
    // or manually recorded by a user.
    isSuggested: {
      type: Boolean,
      default: false,
    },
  },
  { timestamps: true }
);

settlementSchema.index({ group: 1, status: 1 });
settlementSchema.index({ from: 1, to: 1 });

module.exports = mongoose.model('Settlement', settlementSchema);
